name: build

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - 'v*'
  pull_request:

jobs:
  build:
    name: Build Checkmk package
    runs-on: ubuntu-latest
    container:
      image: checkmk/check-mk-raw:2.3.0-latest

    steps:
      - name: Initialize Checkmk Site
        run: /docker-entrypoint.sh /bin/true
      - uses: actions/checkout@v4
      - name: Parse Package File
        run: |
          NAME=$(python3 -c 'print(eval(open("package").read())["name"])')
          VERSION=$(python3 -c 'print(eval(open("package").read())["version"])')
          echo "CMKPKG_NAME=$NAME" >> "$GITHUB_ENV"
          echo "CMKPKG_VERSION=$VERSION" >> "$GITHUB_ENV"
      - name: Install Plugin
        run: |
          rsync -aC --chown=cmk:cmk $GITHUB_WORKSPACE/ /omd/sites/cmk/local/lib/python3/cmk_addons/plugins/$CMKPKG_NAME/
      - name: Build Extension
        run: |
          su -l -c "mkp -v package $GITHUB_WORKSPACE/package" cmk
          cp /omd/sites/cmk/var/check_mk/packages_local/${CMKPKG_NAME}-${CMKPKG_VERSION}.mkp .
          echo "pkgfile=${CMKPKG_NAME}-${CMKPKG_VERSION}.mkp" >> $GITHUB_OUTPUT
          echo "pkgname=${CMKPKG_NAME}" >> $GITHUB_OUTPUT
          echo "pkgversion=${CMKPKG_VERSION}" >> $GITHUB_OUTPUT
        id: cmkpkg
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.cmkpkg.outputs.pkgfile }}
          path: ${{ steps.cmkpkg.outputs.pkgfile }}
