name: pytest

on:
  push:
    paths:
      - '**.py'
      - .github/workflows/pytest.yml

jobs:
  pytest:

    runs-on: ubuntu-latest
    container:
      image: checkmk/check-mk-raw:2.3.0-latest

    steps:
      - name: Initialize Checkmk Site
        run: /docker-entrypoint.sh /bin/true
      - uses: actions/checkout@v4
      - name: Parse Package File
        run: |
          NAME=$(python3 -c 'print(eval(open("package").read())["name"])')
          VERSION=$(python3 -c 'print(eval(open("package").read())["version"])')
          echo "CMKPKG_NAME=$NAME" >> "$GITHUB_ENV"
          echo "CMKPKG_VERSION=$VERSION" >> "$GITHUB_ENV"
      - name: Install Plugin
        run: |
          rsync -aC --chown=cmk:cmk $GITHUB_WORKSPACE/ /omd/sites/cmk/local/lib/python3/cmk_addons/plugins/$CMKPKG_NAME/
      - name: Install pytest
        run: su -l -c "REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt pip3 install -r $GITHUB_WORKSPACE/.devcontainer/requirements.txt" cmk
      - name: Run pytest
        run: su -l -c "python3 -m pytest /omd/sites/cmk/local/lib/python3/cmk_addons/plugins/$CMKPKG_NAME/" cmk